sudo: required
dist: trusty

language: cpp

notifications:
  email:
      - jkmtravisnotify@gmail.com

compiler: gcc

branches:
  only:
    - develop
    - master


before_install:
  # print the distro information
  - lsb_release -a

  # cache refresh required to install packages
  - sudo apt-get update -qq

  # install dependencies
  - sudo apt-get -y install cmake swig python-dev python-numpy llvm-3.5-dev

  - mkdir ~/install

  # install roadrunner dependencies via apt:
  - sudo sh -c 'echo "\n\ndeb http://cdn.rawgit.com/sys-bio/roadrunner-debs/master ./ \n\n" >> /etc/apt/sources.list'
  - sudo cat /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get -y --force-yes install libroadrunner-deps-dev

  - echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
  # build roadrunner:
  - mkdir -p ~/build/roadrunner

install:
  - cd ~/build/roadrunner
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install/roadrunner -DTHIRD_PARTY_INSTALL_FOLDER=/usr -DLLVM_CONFIG_EXECUTABLE=/usr/lib/llvm-3.5/bin/llvm-config -DBUILD_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so python2.7 -DBUILD_TESTS=ON -DBUILD_TEST_TOOLS=ON -DUSE_TR1_CXX_NS=ON -DBUILD_JAVA_INTERFACE=OFF "$TRAVIS_BUILD_DIR"
  - make -j2
  - make install

before_script: true

script:
  - cd ~/build/roadrunner
  - make -j2 && make install
  - ctest -VV
  # display results of compiled tests
  - cat autotest/compiled-test-suite/results.xml
