sudo: required
dist: xenial

language: cpp

notifications:
email:
- jkmtravisnotify@gmail.com

compiler: gcc

branches:
only:
- develop
- master
- llvm-6
- issue-534

before_install:
# print the distro information
- lsb_release -a

# cache refresh required to install packages
- sudo apt-get update -qq

# install dependencies
- sudo apt-get -y install cmake swig python-dev python-numpy llvm-6.0-dev

# install roadrunner dependencies via apt:
- mkdir ~/debs
- cd ~/debs

- wget   https://github.com/andrewbriand/debs-recompile-for-travis/blob/master/libroadrunner-deps_2.0.8_amd64.deb?raw=true
- mv libroadrunner-deps_2.0.8_amd64.deb?raw=true libroadrunner-deps_2.0.8_amd64.deb
- sudo dpkg -i libroadrunner-deps_2.0.8_amd64.deb
- wget   https://github.com/andrewbriand/debs-recompile-for-travis/blob/master/libroadrunner-deps-dev_2.0.8_amd64.deb?raw=true
- mv libroadrunner-deps-dev_2.0.8_amd64.deb?raw=true libroadrunner-deps-dev_2.0.8_amd64.deb
- sudo dpkg -i libroadrunner-deps-dev_2.0.8_amd64.deb
#- sudo cp /usr/local/include/rr-libstruct/* /usr/local/include
#- sudo cp /usr/local/include/clapack/* /usr/local/include

# Get package name
- dpkg --info libroadrunner-deps_2.0.8_amd64.deb | grep Package
- dpkg -L libroadrunner-deps
- dpkg --info libroadrunner-deps-dev_2.0.8_amd64.deb | grep Package
- dpkg -L libroadrunner-deps-dev

- mkdir ~/install

- echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
# build roadrunner:
- mkdir -p ~/build/roadrunner

install:
- cd ~/build/roadrunner
# consider changing to python3
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install/roadrunner -DTHIRD_PARTY_INSTALL_FOLDER=/usr -DLLVM_CONFIG_EXECUTABLE=/usr/lib/llvm-6.0/bin/llvm-config -DBUILD_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so python2.7 -DBUILD_TESTS=ON -DBUILD_TEST_TOOLS=ON -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=1' -DUSE_TR1_CXX_NS=OFF -DRR_USE_CXX14=OFF -DBUILD_JAVA_INTERFACE=OFF -DSWIG_DIR=/usr/share/swig3.0 "$TRAVIS_BUILD_DIR"
- make clean
- make -j2
- make install

before_script: true

script:
  - cd ~/build/roadrunner
  - make -j2 && make install
  - ./bin/cxx_api_tests -m ~/build/sys-bio/roadrunner/models/sbml-test-suite -r tests.out -t autotest/compiled-test-suite/ 
  - ctest -V
  # display results of compiled tests
  - cat autotest/compiled-test-suite/results.xml
  - cat tests.out
