# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - develop
  - azure-test

pr:
  - master
  - develop
  - azure-test

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2019-windows2019'
    steps:
      - script: echo hello from Windows
  - job: macOS
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - script: echo hello from macOS
  - job: Linux
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: |
          echo "Hello world from $AGENT_NAME running on $AGENT_OS"
          wget https://github.com/sys-bio/llvm-6.x/releases/download/release%2F6.x/llvm-6.x-gcc7.5.0-x64-release.tar.gz
          tar zxvf llvm-6.x-gcc7.5.0-x64-release.tar.gz

      - displayName: GetLLVM

#
#    displayName: 'Build roadrunner dependencies on Linux'
#    pool:
#      vmImage: 'ubuntu-18.04'
#    steps:
#      - script: bash $(pwd)/ci/build-linux.sh

