# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- azure-test

pool:
  vmImage: 'ubuntu-latest'

container: ciaranwelsh/roadrunner-build:latest

steps:
- script: bash $(pwd)/ci/build-linux.sh
  displayName: 'Build roadrunner dependencies on Linux'

