Document: libroadrunner
Title: Debian libroadrunner Manual
Author: <insert document author here>
Abstract: This manual describes what libroadrunner is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libroadrunner/libroadrunner.sgml.gz

Format: postscript
Files: /usr/share/doc/libroadrunner/libroadrunner.ps.gz

Format: text
Files: /usr/share/doc/libroadrunner/libroadrunner.text.gz

Format: HTML
Index: /usr/share/doc/libroadrunner/html/index.html
Files: /usr/share/doc/libroadrunner/html/*.html
