@startuml
'https://plantuml.com/class-diagram

class Solver #aqua-white

class Integrator #aqua-white

Solver <|-- Integrator

class SteadyStateSolver #aqua-white

Solver <|-- SteadyStateSolver

class NLEQ1 #LightGreen-white
class NLEQ2 #LightGreen-white

SteadyStateSolver <|-- NLEQ1
SteadyStateSolver <|-- NLEQ2

class CVODEIntegrator #LightGreen-white
class GillespieIntegrator #LightGreen-white
class EulerIntegrator #LightGreen-white
class RK5Integrator #LightGreen-white
class RK45Integrator #LightGreen-white

Integrator <|-- CVODEIntegrator
Integrator <|-- GillespieIntegrator
Integrator <|-- EulerIntegrator
Integrator <|-- RK5Integrator
Integrator <|-- RK45Integrator

class IntegratorFactory #aqua-white


class IntegratorRegistrar #aqua-white
class CVODEIntegratorRegistrar #LightGreen-white
class GillespieIntegratorRegistrar #LightGreen-white
class EulerIntegratorRegistrar #LightGreen-white
class RK5IntegratorRegistrar #LightGreen-white
class RK45IntegratorRegistrar #LightGreen-white

IntegratorRegistrar <|-- CVODEIntegratorRegistrar
IntegratorRegistrar <|-- GillespieIntegratorRegistrar
IntegratorRegistrar <|-- EulerIntegratorRegistrar
IntegratorRegistrar <|-- RK5IntegratorRegistrar
IntegratorRegistrar <|-- RK45IntegratorRegistrar


Integrator *-- IntegratorRegistrar

IntegratorFactory *-- IntegratorRegistrar

class RoadRunner #red-white

RoadRunner *-- IntegratorFactory


class SteadyStateSolverRegistrar #aqua-white
class SteadyStateSolverFactory #aqua-white

SteadyStateSolverFactory *-- SteadyStateSolverRegistrar

RoadRunner *-- SteadyStateSolverFactory

SteadyStateSolver *-- SteadyStateSolverRegistrar

class NLEQ1Registrar #LightGreen-white
class NLEQ2Registrar #LightGreen-white

SteadyStateSolverRegistrar <|-- NLEQ1Registrar
SteadyStateSolverRegistrar <|-- NLEQ2Registrar



class SundialsSteadyStateSolver

SteadyStateSolver <|-- SundialsSteadyStateSolver

class NewtonIteration
class BasicNewtonIteration
class LineSearchNewtonIteration


class FixedPointIteration
note top of FixedPointIteration {
    Still needs work
}

SundialsSteadyStateSolver <|-- NewtonIteration
NewtonIteration <|-- BasicNewtonIteration
NewtonIteration <|-- LineSearchNewtonIteration
SundialsSteadyStateSolver <|-- FixedPointIteration











'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

@enduml