@startuml
'https://plantuml.com/class-diagram


class SteadyStateSolver

class SundialsSteadyStateSolver

SteadyStateSolver <|-- SundialsSteadyStateSolver

class NLEQSolver

SteadyStateSolver <|-- NLEQSolver

class NLEQ1

class NLEQ2

NLEQSolver <|-- NLEQ1
NLEQSolver <|-- NLEQ2

class NewtonIteration {
    inexact: bool
    modified: bool
}

class PicardIteration

class FixedPointIteration {
    withAndersonAcceleration: bool
}

SundialsSteadyStateSolver <|-- NewtonIteration
SundialsSteadyStateSolver <|-- PicardIteration
SundialsSteadyStateSolver <|-- FixedPointIteration


class Presimulation

note left of Presimulation{
    Used by
    all steady
    state solvers.
    Dependency
    injection.
}









@enduml