@startuml
'https://plantuml.com/class-diagram


class SteadyStateSolver

class SundialsSteadyStateSolver

SteadyStateSolver <|-- SundialsSteadyStateSolver

class NewtonIteration {
    inexact: bool
    modified: bool
}

class PicardIteration

class FixedPointIteration {
    withAndersonAcceleration: bool
}

SundialsSteadyStateSolver <|-- NewtonIteration
SundialsSteadyStateSolver <|-- PicardIteration
SundialsSteadyStateSolver <|-- FixedPointIteration












@enduml