#ifndef rr_version_infoH
#define rr_version_infoH
/*This file is autogenerated by the build system. Any modifications will be overwritten on the next build */
const char* RR_VERSION =  "1.0.0";

#endif