Document: libroadrunner-deps
Title: Debian libroadrunner-deps Manual
Author: <insert document author here>
Abstract: This manual describes what libroadrunner-deps is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libroadrunner-deps/libroadrunner-deps.sgml.gz

Format: postscript
Files: /usr/share/doc/libroadrunner-deps/libroadrunner-deps.ps.gz

Format: text
Files: /usr/share/doc/libroadrunner-deps/libroadrunner-deps.text.gz

Format: HTML
Index: /usr/share/doc/libroadrunner-deps/html/index.html
Files: /usr/share/doc/libroadrunner-deps/html/*.html
