//
// Created by Ciaran on 17/05/2021.
//

#include "Brown2004.h"


std::string Brown2004::str() {
    return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
           "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version1/core\" level=\"3\" version=\"1\">\n"
           "  <model metaid=\"Brown2004_NGF_EGF_signaling\" id=\"Brown2004_NGF_EGF_signaling\">\n"
           "    <listOfCompartments>\n"
           "      <compartment id=\"cell\" spatialDimensions=\"3\" size=\"1\" constant=\"true\"/>\n"
           "    </listOfCompartments>\n"
           "    <listOfSpecies>\n"
           "      <species id=\"EGF\" compartment=\"cell\" initialConcentration=\"10002000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"NGF\" compartment=\"cell\" initialConcentration=\"456000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"freeEGFReceptor\" compartment=\"cell\" initialConcentration=\"80000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"boundEGFReceptor\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"freeNGFReceptor\" compartment=\"cell\" initialConcentration=\"10000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"boundNGFReceptor\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"SosInactive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"SosActive\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"P90RskInactive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"P90RskActive\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"RasInactive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"RasActive\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"RasGapActive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"true\" constant=\"false\"/>\n"
           "      <species id=\"Raf1Inactive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"Raf1Active\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"BRafInactive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"BRafActive\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"MekInactive\" compartment=\"cell\" initialConcentration=\"600000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"MekActive\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"ErkInactive\" compartment=\"cell\" initialConcentration=\"600000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"ErkActive\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"PI3KInactive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"PI3KActive\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"AktInactive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"AktActive\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"C3GInactive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"C3GActive\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"Rap1Inactive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"Rap1Active\" compartment=\"cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
           "      <species id=\"RapGapActive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"true\" constant=\"false\"/>\n"
           "      <species id=\"PP2AActive\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"true\" constant=\"false\"/>\n"
           "      <species id=\"Raf1PPtase\" compartment=\"cell\" initialConcentration=\"120000\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"true\" constant=\"false\"/>\n"
           "    </listOfSpecies>\n"
           "    <listOfParameters>\n"
           "      <parameter id=\"krbEGF\" value=\"2.18503e-05\" constant=\"true\"/>\n"
           "      <parameter id=\"kruEGF\" value=\"0.0121008\" constant=\"true\"/>\n"
           "      <parameter id=\"krbNGF\" value=\"1.38209e-07\" constant=\"true\"/>\n"
           "      <parameter id=\"kruNGF\" value=\"0.00723811\" constant=\"true\"/>\n"
           "      <parameter id=\"kEGF\" value=\"694.731\" constant=\"true\"/>\n"
           "      <parameter id=\"KmEGF\" value=\"6086070\" constant=\"true\"/>\n"
           "      <parameter id=\"kNGF\" value=\"389.428\" constant=\"true\"/>\n"
           "      <parameter id=\"KmNGF\" value=\"2112.66\" constant=\"true\"/>\n"
           "      <parameter id=\"kdSos\" value=\"1611.97\" constant=\"true\"/>\n"
           "      <parameter id=\"KmdSos\" value=\"896896\" constant=\"true\"/>\n"
           "      <parameter id=\"kSos\" value=\"32.344\" constant=\"true\"/>\n"
           "      <parameter id=\"KmSos\" value=\"35954.3\" constant=\"true\"/>\n"
           "      <parameter id=\"kRasGap\" value=\"1509.36\" constant=\"true\"/>\n"
           "      <parameter id=\"KmRasGap\" value=\"1432410\" constant=\"true\"/>\n"
           "      <parameter id=\"kRasToRaf1\" value=\"0.884096\" constant=\"true\"/>\n"
           "      <parameter id=\"KmRasToRaf1\" value=\"62464.6\" constant=\"true\"/>\n"
           "      <parameter id=\"kpRaf1\" value=\"185.759\" constant=\"true\"/>\n"
           "      <parameter id=\"KmpRaf1\" value=\"4768350\" constant=\"true\"/>\n"
           "      <parameter id=\"kpBRaf\" value=\"125.089\" constant=\"true\"/>\n"
           "      <parameter id=\"KmpBRaf\" value=\"157948\" constant=\"true\"/>\n"
           "      <parameter id=\"kpMekCytoplasmic\" value=\"9.85367\" constant=\"true\"/>\n"
           "      <parameter id=\"KmpMekCytoplasmic\" value=\"1007340\" constant=\"true\"/>\n"
           "      <parameter id=\"kdMek\" value=\"2.83243\" constant=\"true\"/>\n"
           "      <parameter id=\"KmdMek\" value=\"518753\" constant=\"true\"/>\n"
           "      <parameter id=\"kdErk\" value=\"8.8912\" constant=\"true\"/>\n"
           "      <parameter id=\"KmdErk\" value=\"3496490\" constant=\"true\"/>\n"
           "      <parameter id=\"kdRaf1\" value=\"0.126329\" constant=\"true\"/>\n"
           "      <parameter id=\"KmdRaf1\" value=\"1061.71\" constant=\"true\"/>\n"
           "      <parameter id=\"kpP90Rsk\" value=\"0.0213697\" constant=\"true\"/>\n"
           "      <parameter id=\"KmpP90Rsk\" value=\"763523\" constant=\"true\"/>\n"
           "      <parameter id=\"kPI3K\" value=\"10.6737\" constant=\"true\"/>\n"
           "      <parameter id=\"KmPI3K\" value=\"184912\" constant=\"true\"/>\n"
           "      <parameter id=\"kPI3KRas\" value=\"0.0771067\" constant=\"true\"/>\n"
           "      <parameter id=\"KmPI3KRas\" value=\"272056\" constant=\"true\"/>\n"
           "      <parameter id=\"kAkt\" value=\"0.0566279\" constant=\"true\"/>\n"
           "      <parameter id=\"KmAkt\" value=\"653951\" constant=\"true\"/>\n"
           "      <parameter id=\"kdRaf1ByAkt\" value=\"15.1212\" constant=\"true\"/>\n"
           "      <parameter id=\"KmRaf1ByAkt\" value=\"119355\" constant=\"true\"/>\n"
           "      <parameter id=\"kC3GNGF\" value=\"146.912\" constant=\"true\"/>\n"
           "      <parameter id=\"KmC3GNGF\" value=\"12876.2\" constant=\"true\"/>\n"
           "      <parameter id=\"kC3G\" value=\"1.40145\" constant=\"true\"/>\n"
           "      <parameter id=\"KmC3G\" value=\"10965.6\" constant=\"true\"/>\n"
           "      <parameter id=\"kRapGap\" value=\"27.265\" constant=\"true\"/>\n"
           "      <parameter id=\"KmRapGap\" value=\"295990\" constant=\"true\"/>\n"
           "      <parameter id=\"kRap1ToBRaf\" value=\"2.20995\" constant=\"true\"/>\n"
           "      <parameter id=\"KmRap1ToBRaf\" value=\"1025460\" constant=\"true\"/>\n"
           "      <parameter id=\"kdBRaf\" value=\"441.287\" constant=\"true\"/>\n"
           "      <parameter id=\"KmdBRaf\" value=\"10879500\" constant=\"true\"/>\n"
           "    </listOfParameters>\n"
           "    <listOfReactions>\n"
           "      <reaction id=\"EGFBindingReaction\" reversible=\"false\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"EGF\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "          <speciesReference species=\"freeEGFReceptor\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"boundEGFReceptor\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <ci> krbEGF </ci>\n"
           "              <ci> EGF </ci>\n"
           "              <ci> freeEGFReceptor </ci>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"EGFUnbindingReaction\" reversible=\"false\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"boundEGFReceptor\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"EGF\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "          <speciesReference species=\"freeEGFReceptor\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <ci> kruEGF </ci>\n"
           "              <ci> boundEGFReceptor </ci>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"NGFBindingReaction\" reversible=\"false\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"NGF\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "          <speciesReference species=\"freeNGFReceptor\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"boundNGFReceptor\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> krbNGF </ci>\n"
           "              <ci> NGF </ci>\n"
           "              <ci> freeNGFReceptor </ci>\n"
           "              <ci> cell </ci>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"NGFUnbindingReaction\" reversible=\"false\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"boundNGFReceptor\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"NGF\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "          <speciesReference species=\"freeNGFReceptor\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> kruNGF </ci>\n"
           "              <ci> boundNGFReceptor </ci>\n"
           "              <ci> cell </ci>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"SosActivationByEGFReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"SosInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"SosActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"boundEGFReceptor\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kEGF </ci>\n"
           "                  <ci> boundEGFReceptor </ci>\n"
           "                  <ci> SosInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> SosInactive </ci>\n"
           "                  <ci> KmEGF </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"SosActivationByNGFReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"SosInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"SosActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"boundNGFReceptor\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kNGF </ci>\n"
           "                  <ci> boundNGFReceptor </ci>\n"
           "                  <ci> SosInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> SosInactive </ci>\n"
           "                  <ci> KmNGF </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"SosDeactivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"SosActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"SosInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"P90RskActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kdSos </ci>\n"
           "                  <ci> P90RskActive </ci>\n"
           "                  <ci> SosActive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> SosActive </ci>\n"
           "                  <ci> KmdSos </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"RasActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"RasInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"RasActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"SosActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kSos </ci>\n"
           "                  <ci> SosActive </ci>\n"
           "                  <ci> RasInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> RasInactive </ci>\n"
           "                  <ci> KmSos </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"RasDeactivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"RasActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"RasInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"RasGapActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kRasGap </ci>\n"
           "                  <ci> RasGapActive </ci>\n"
           "                  <ci> RasActive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> RasActive </ci>\n"
           "                  <ci> KmRasGap </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"Raf1ByRasActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"Raf1Inactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"Raf1Active\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"RasActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kRasToRaf1 </ci>\n"
           "                  <ci> RasActive </ci>\n"
           "                  <ci> Raf1Inactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> Raf1Inactive </ci>\n"
           "                  <ci> KmRasToRaf1 </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"MekbyRaf1ActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"MekInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"MekActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"Raf1Active\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kpRaf1 </ci>\n"
           "                  <ci> Raf1Active </ci>\n"
           "                  <ci> MekInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> MekInactive </ci>\n"
           "                  <ci> KmpRaf1 </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"MekbyBRafActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"MekInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"MekActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"BRafActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kpBRaf </ci>\n"
           "                  <ci> BRafActive </ci>\n"
           "                  <ci> MekInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> MekInactive </ci>\n"
           "                  <ci> KmpBRaf </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"ErkActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"ErkInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"ErkActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"MekActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kpMekCytoplasmic </ci>\n"
           "                  <ci> MekActive </ci>\n"
           "                  <ci> ErkInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> ErkInactive </ci>\n"
           "                  <ci> KmpMekCytoplasmic </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"MekDeactivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"MekActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"MekInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"PP2AActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kdMek </ci>\n"
           "                  <ci> PP2AActive </ci>\n"
           "                  <ci> MekActive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> MekActive </ci>\n"
           "                  <ci> KmdMek </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"ErkDeactivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"ErkActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"ErkInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"PP2AActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kdErk </ci>\n"
           "                  <ci> PP2AActive </ci>\n"
           "                  <ci> ErkActive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> ErkActive </ci>\n"
           "                  <ci> KmdErk </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"Raf1byPPtaseDeactivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"Raf1Active\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"Raf1Inactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"Raf1PPtase\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kdRaf1 </ci>\n"
           "                  <ci> Raf1PPtase </ci>\n"
           "                  <ci> Raf1Active </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> Raf1Active </ci>\n"
           "                  <ci> KmdRaf1 </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"P90RskActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"P90RskInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"P90RskActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"ErkActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kpP90Rsk </ci>\n"
           "                  <ci> ErkActive </ci>\n"
           "                  <ci> P90RskInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> P90RskInactive </ci>\n"
           "                  <ci> KmpP90Rsk </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"PI3KbyEGFRActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"PI3KInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"PI3KActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"boundEGFReceptor\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kPI3K </ci>\n"
           "                  <ci> boundEGFReceptor </ci>\n"
           "                  <ci> PI3KInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> PI3KInactive </ci>\n"
           "                  <ci> KmPI3K </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"PI3KbyRasActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"PI3KInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"PI3KActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"RasActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kPI3KRas </ci>\n"
           "                  <ci> RasActive </ci>\n"
           "                  <ci> PI3KInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> PI3KInactive </ci>\n"
           "                  <ci> KmPI3KRas </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"AktActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"AktInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"AktActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"PI3KActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kAkt </ci>\n"
           "                  <ci> PI3KActive </ci>\n"
           "                  <ci> AktInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> AktInactive </ci>\n"
           "                  <ci> KmAkt </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"Raf1ByAktDeactivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"Raf1Active\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"Raf1Inactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"AktActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kdRaf1ByAkt </ci>\n"
           "                  <ci> AktActive </ci>\n"
           "                  <ci> Raf1Active </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> Raf1Active </ci>\n"
           "                  <ci> KmRaf1ByAkt </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"C3GActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"C3GInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"C3GActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"boundNGFReceptor\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kC3GNGF </ci>\n"
           "                  <ci> boundNGFReceptor </ci>\n"
           "                  <ci> C3GInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> C3GInactive </ci>\n"
           "                  <ci> KmC3GNGF </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"Rap1ActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"Rap1Inactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"Rap1Active\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"C3GActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kC3G </ci>\n"
           "                  <ci> C3GActive </ci>\n"
           "                  <ci> Rap1Inactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> Rap1Inactive </ci>\n"
           "                  <ci> KmC3G </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"Rap1DeactivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"Rap1Active\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"Rap1Inactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"RapGapActive\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kRapGap </ci>\n"
           "                  <ci> RapGapActive </ci>\n"
           "                  <ci> Rap1Active </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> Rap1Active </ci>\n"
           "                  <ci> KmRapGap </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"BRafByRap1ActivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"BRafInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"BRafActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"Rap1Active\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kRap1ToBRaf </ci>\n"
           "                  <ci> Rap1Active </ci>\n"
           "                  <ci> BRafInactive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> BRafInactive </ci>\n"
           "                  <ci> KmRap1ToBRaf </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "      <reaction id=\"BRafbyPPtaseDeactivationReaction\" reversible=\"true\" fast=\"false\">\n"
           "        <listOfReactants>\n"
           "          <speciesReference species=\"BRafActive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfReactants>\n"
           "        <listOfProducts>\n"
           "          <speciesReference species=\"BRafInactive\" stoichiometry=\"1\" constant=\"true\"/>\n"
           "        </listOfProducts>\n"
           "        <listOfModifiers>\n"
           "          <modifierSpeciesReference species=\"Raf1PPtase\"/>\n"
           "        </listOfModifiers>\n"
           "        <kineticLaw>\n"
           "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
           "            <apply>\n"
           "              <times/>\n"
           "              <ci> cell </ci>\n"
           "              <apply>\n"
           "                <divide/>\n"
           "                <apply>\n"
           "                  <times/>\n"
           "                  <ci> kdBRaf </ci>\n"
           "                  <ci> Raf1PPtase </ci>\n"
           "                  <ci> BRafActive </ci>\n"
           "                </apply>\n"
           "                <apply>\n"
           "                  <plus/>\n"
           "                  <ci> BRafActive </ci>\n"
           "                  <ci> KmdBRaf </ci>\n"
           "                </apply>\n"
           "              </apply>\n"
           "            </apply>\n"
           "          </math>\n"
           "        </kineticLaw>\n"
           "      </reaction>\n"
           "    </listOfReactions>\n"
           "  </model>\n"
           "</sbml>";
}

std::string Brown2004::modelName() {
    return "Brown2004";
}

/**
 * Copasi output:
 *
 *
 */
StringDoubleMap Brown2004::steadyState() {
    return StringDoubleMap{
            {"EGF",              9922004.46501588},
            {"NGF",              447048.6328396933},
            {"freeEGFReceptor",  4.465015881563886},
            {"boundEGFReceptor", 79995.53498411844},
            {"freeNGFReceptor",  1048.632839693278},
            {"boundNGFReceptor", 8951.367160306723},
            {"SosInactive",      99569.9548813399},
            {"SosActive",        20430.0451186601},
            {"P90RskInactive",   0},
            {"P90RskActive",     120000},
            {"RasInactive",      115999.51997363668},
            {"RasActive",        4000.4800263633224},
            {"Raf1Inactive",     119918.26132477315},
            {"Raf1Active",       81.73867522685032},
            {"BRafInactive",     119315.8938154474},
            {"BRafActive",       684.1061845525983},
            {"MekInactive",      475871.3129791245},
            {"MekActive",        124128.68702087551},
            {"ErkInactive",      118834.97021061042},
            {"ErkActive",        481165.02978938946},
            {"PI3KInactive",     0},
            {"PI3KActive",       119999.99999999997},
            {"AktInactive",      0},
            {"AktActive",        120000},
            {"C3GInactive",      0},
            {"C3GActive",        120000},
            {"Rap1Inactive",     105544.62439152892},
            {"Rap1Active",       14455.37560847107},
    };

};

std::unordered_map<std::string, rr::Setting> Brown2004::steadyStateSettings() {
    return std::unordered_map<std::string, rr::Setting>{
            {"allow_presimulation", true},
            // this model can converge to a set of values different to the reference data,
            // depending on starting values. For this reason, start the list of presimulation
            // times at a larger number.
            {"presimulation_times", std::vector<double>({10, 100, 1000})}
    };
}

