//
// Created by Ciaran on 14/03/2021.
//

#ifndef ROADRUNNER_APPROXSTEADYSTATEDECORATOR_H
#define ROADRUNNER_APPROXSTEADYSTATEDECORATOR_H


class ApproxSteadyStateDecorator {

};


#endif //ROADRUNNER_APPROXSTEADYSTATEDECORATOR_H
